### ISSUE TITLE
Missing .phpcs file

### ISSUE THREAD

**Issue by robert-scheck** [grommunio/mapi-header-php#1]
As of writing [README.md](https://github.com/grommunio/mapi-header-php/blob/master/README.md) says:

> This repository follows a customized coding style. The coding style can be validated anytime by the repositories provided [configuration file](https://github.com/grommunio/mapi-header-php/blob/master/.phpcs).

However, the mentioned [.phpcs](https://github.com/grommunio/mapi-header-php/blob/master/.phpcs) does not exist.

**Comment by grammmike** [comment]
good catch. included with https://github.com/grommunio/mapi-header-php/commit/a61fbdd379ab201943f9fcabe9ea037f5f31d0fc, updated with https://github.com/grommunio/mapi-header-php/commit/24e7889083a723d7ee8fb2c1c5022128143a551b and applied with https://github.com/grommunio/mapi-header-php/commit/fa6b775ba3c7991c5e4fb9a0d7aac7e74c698cee
